version: 2

project_name: kustomize-traverse

before:
  hooks:
    - go mod tidy

builds:
  - id: kustomize-traverse
    main: .
    binary: kustomize-traverse
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    formats: [tar.gz]
    files:
      - LICENSE*
      - README*
      - SPEC*

checksum:
  name_template: "checksums-sha256.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: Yolean
    name: kustomize-traverse
