// Code generated by scripts/buildctl-refresh.sh from github.com/moby/buildkit@v0.33.1 cmd/buildctl. DO NOT EDIT.

//go:build !windows

package buildctl

import (
	"syscall"

	copy "github.com/tonistiigi/fsutil/copy"
)

func init_main_unix() {
	syscall.Umask(0)
	copy.UmaskIsZero = true
}
