// Code generated by scripts/buildctl-refresh.sh from github.com/moby/buildkit@v0.33.1 cmd/buildctl. DO NOT EDIT.

// Package buildctl is BuildKit's buildctl command, compiled into y-cluster.
// Licensed under the Apache License 2.0 (LICENSE in this directory).
package buildctl

import "github.com/moby/buildkit/version"

// Version is the BuildKit release this copy of buildctl comes from.
const Version = "v0.33.1"

// Main runs buildctl with args, args[0] being the program name, and
// exits the process on error as buildctl does.
func Main(args []string) {
	// set by BuildKit's release build, unset in a module dependency
	version.Version = Version
	init_main()
	init_main_unix()
	main(args)
}
