// Package gateway exposes a maintainer-facing snapshot of the
// y-cluster Gateway API state in the cluster: the GatewayClass,
// the Gateway resources and their reconciled listener status,
// HTTPRoute / GRPCRoute attachments + filters, and Envoy Gateway
// extension policies (ClientTrafficPolicy, BackendTrafficPolicy)
// that affect maintenance-relevant runtime behavior such as XFF
// trust + client-IP detection.
//
// The snapshot is deliberately RECONCILED -- every kind is read
// from the cluster post-controller (kubectl get -o json includes
// .status), not derived from the operator's source-of-truth
// kustomize. That distinction matters for maintenance: the spec
// says "trust 1 XFF hop"; the status says whether envoy-gateway
// accepted the policy and is actually applying it. A cluster
// where a ClientTrafficPolicy is rejected reports the spec but
// shows Accepted=False on the status, which a downstream
// consumer can flag.
//
// The package is also responsible for a small write operation:
// clearing the yolean.se/dns-hint-ip GatewayClass annotation
// before an appliance is exported, so the per-deploy IP is not
// baked into the customer's snapshot. This belongs here because
// the dns-hint annotation is part of the gateway's surface, not
// the lifecycle of the cluster itself.
package gateway

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os/exec"
	"strings"
	"time"

	"github.com/Yolean/y-cluster/pkg/provision/envoygateway"
)

// SchemaID is the canonical $id for the generated JSON Schema.
// Kept in sync with the file at pkg/gateway/state.schema.json
// (regenerated by `go generate ./pkg/provision/...`).
//
// The URL is intentionally UNVERSIONED -- it always points at the
// current schema doc. Per-document version comes from
// SchemaVersion below, which the schema constrains to a single
// value via an enum-of-one. Bumping the schema (a backward-
// incompatible change to the JSON shape) means: increment
// SchemaVersion, update the schemagen post-process to enum the
// new value, regenerate the schema. Old snapshots remain
// readable + identifiable by their schemaVersion field; new
// snapshots are flagged by the new enum value.
const SchemaID = "https://yolean.se/y-cluster/schema/gateway-state.schema.json"

// SchemaVersion is the current snapshot-shape version. Bumped
// when the JSON shape of State changes in a backward-incompatible
// way (e.g. removing or renaming a field). Additive changes
// (new optional field with omitempty) do NOT require a bump.
const SchemaVersion = "1"

// State is the top-level snapshot a y-cluster gateway state call
// produces. The shape is a stable contract -- consumers (the
// appliance's gateway-state.json bundled at prepare-export, the
// y-cluster gateway state CLI, future hosting integrations)
// depend on it. New fields are added (with omitempty) without
// breaking them; existing fields are not renamed or retyped.
type State struct {
	// GatewayClass identifies the cluster's y-cluster gateway
	// class plus its (post-clean) annotations + reconciliation
	// status. Returned even when no Gateway has been created
	// yet, so consumers can verify the cluster reached the
	// envoygateway.Install step.
	GatewayClass *GatewayClass `json:"gatewayClass,omitempty"`

	// Gateways are all Gateway resources in the cluster
	// (cluster-scoped enumeration). Includes the y-cluster
	// shipped Gateway plus any consumer-defined ones.
	Gateways []Gateway `json:"gateways"`

	// HTTPRoutes are all HTTPRoute resources in the cluster.
	// Each carries enough rule/filter detail for a consumer
	// to tell "this port is redirect-only" from "this port
	// serves real traffic".
	HTTPRoutes []HTTPRoute `json:"httpRoutes"`

	// GRPCRoutes mirrors HTTPRoutes for the gRPC kind.
	GRPCRoutes []GRPCRoute `json:"grpcRoutes"`

	// ClientTrafficPolicies are envoy-gateway extension
	// resources that adjust client-side listener behavior --
	// the canonical example is xForwardedFor.numTrustedHops
	// (controls whether envoy trusts an upstream LB's
	// X-Forwarded-Proto). Status conditions tell whether the
	// policy was accepted into the listener config.
	ClientTrafficPolicies []ClientTrafficPolicy `json:"clientTrafficPolicies"`

	// BackendTrafficPolicies mirror their client-side siblings
	// for backend-bound behavior.
	BackendTrafficPolicies []BackendTrafficPolicy `json:"backendTrafficPolicies"`

	// Envoy is a sample of dataplane state from one
	// envoy-gateway proxy pod (version + verbatim
	// /config_dump). Best-effort and optional: nil when no
	// proxy pod is reachable. Consumers needing dataplane
	// ground-truth (the actually-programmed envoy config) read
	// this; consumers wanting the reconciled k8s view read the
	// per-kind slices above.
	Envoy *Envoy `json:"envoy,omitempty"`

	// Summary is a fully-typed, industry-term projection of
	// the routing tree (listener -> host -> route ->
	// match/backend) derived deterministically from the
	// per-kind slices. The k8s-side data is the source of
	// truth; Summary is the ergonomic view on top.
	Summary *Summary `json:"summary,omitempty"`

	// FetchedAt is the wall-clock at which the snapshot was
	// taken, in RFC 3339 format. Useful when comparing two
	// snapshots taken minutes apart during a debug session.
	FetchedAt string `json:"fetchedAt"`

	// SchemaID is duplicated from the constant above so a
	// snapshot read in isolation knows which schema to
	// validate against without the consumer having to know
	// the y-cluster version that produced it.
	SchemaID string `json:"$schema,omitempty"`

	// SchemaVersion stamps the snapshot with the version of
	// the JSON shape it conforms to. Constrained to a single
	// value (currently "1") via an enum on the generated
	// schema, so a consumer reading the JSON can reject an
	// unexpected version explicitly rather than parse a stale
	// shape blindly. Bumped only on backward-incompatible
	// changes (renames, removals); additive (new omitempty
	// fields) doesn't require it.
	SchemaVersion string `json:"schemaVersion"`
}

// GatewayClass is the partial GatewayClass shape we surface.
// We don't reflect the full upstream type because the
// upstream changes shape across gateway-api versions; the fields
// below are stable across v1alpha2/v1beta1/v1.
type GatewayClass struct {
	Name           string            `json:"name"`
	ControllerName string            `json:"controllerName"`
	Annotations    map[string]string `json:"annotations,omitempty"`
	Labels         map[string]string `json:"labels,omitempty"`
	Conditions     []Condition       `json:"conditions,omitempty"`
}

// Gateway is the partial Gateway shape: enough listener config
// for HTTPS-readiness assessment and enough listener status for
// "did envoy-gateway program this?" answers.
type Gateway struct {
	Namespace        string           `json:"namespace"`
	Name             string           `json:"name"`
	GatewayClassName string           `json:"gatewayClassName"`
	Listeners        []Listener       `json:"listeners"`
	Status           GatewayStatus    `json:"status"`
}

// Listener is the spec-side listener config. TLS and AllowedRoutes
// are passed through as raw JSON so we don't have to chase the
// gateway-api schema's full nested types for fields that are
// pass-through to the consumer.
type Listener struct {
	Name          string          `json:"name"`
	Port          int             `json:"port"`
	Protocol      string          `json:"protocol"`
	Hostname      string          `json:"hostname,omitempty"`
	AllowedRoutes json.RawMessage `json:"allowedRoutes,omitempty"`
	TLS           json.RawMessage `json:"tls,omitempty"`
}

// GatewayStatus carries the reconciled per-listener state.
// AttachedRoutes + Programmed condition together answer "is
// this listener actually serving?".
type GatewayStatus struct {
	Conditions []Condition      `json:"conditions,omitempty"`
	Listeners  []ListenerStatus `json:"listeners,omitempty"`
}

// ListenerStatus is one row of the Gateway's status.listeners
// array.
type ListenerStatus struct {
	Name           string      `json:"name"`
	AttachedRoutes int         `json:"attachedRoutes"`
	Conditions     []Condition `json:"conditions,omitempty"`
	// Programmed surfaces the conventional Programmed=True
	// condition as a boolean for quick consumer checks. False
	// when the condition is missing or its status is anything
	// other than "True".
	Programmed bool `json:"programmed"`
}

// HTTPRoute is the partial HTTPRoute shape. Rules are pass-
// through json.RawMessage so consumers can inspect filters +
// backendRefs without forcing y-cluster to track the full
// upstream rule schema.
type HTTPRoute struct {
	Namespace   string          `json:"namespace"`
	Name        string          `json:"name"`
	ParentRefs  json.RawMessage `json:"parentRefs,omitempty"`
	Hostnames   []string        `json:"hostnames,omitempty"`
	Rules       json.RawMessage `json:"rules,omitempty"`
	Status      RouteStatus     `json:"status"`
}

// GRPCRoute mirrors HTTPRoute for the gRPC kind.
type GRPCRoute struct {
	Namespace  string          `json:"namespace"`
	Name       string          `json:"name"`
	ParentRefs json.RawMessage `json:"parentRefs,omitempty"`
	Hostnames  []string        `json:"hostnames,omitempty"`
	Rules      json.RawMessage `json:"rules,omitempty"`
	Status     RouteStatus     `json:"status"`
}

// RouteStatus normalises both HTTPRoute and GRPCRoute status
// (both use the .status.parents shape).
type RouteStatus struct {
	Parents []RouteParentStatus `json:"parents,omitempty"`
}

// RouteParentStatus is one parent's reconciliation record on a
// route.
type RouteParentStatus struct {
	ParentRef    json.RawMessage `json:"parentRef,omitempty"`
	ControllerName string         `json:"controllerName,omitempty"`
	Conditions   []Condition     `json:"conditions,omitempty"`
}

// ClientTrafficPolicy mirrors envoy-gateway's
// gateway.envoyproxy.io/v1alpha1 ClientTrafficPolicy. The Spec
// field is the full spec object as raw JSON; consumers that
// care about specific knobs (numTrustedHops, trustedCIDRs)
// drill into spec.clientIPDetection.xForwardedFor.
type ClientTrafficPolicy struct {
	Namespace  string          `json:"namespace"`
	Name       string          `json:"name"`
	TargetRefs json.RawMessage `json:"targetRefs,omitempty"`
	Spec       json.RawMessage `json:"spec"`
	Status     PolicyStatus    `json:"status"`
}

// BackendTrafficPolicy mirrors ClientTrafficPolicy on the
// backend side.
type BackendTrafficPolicy struct {
	Namespace  string          `json:"namespace"`
	Name       string          `json:"name"`
	TargetRefs json.RawMessage `json:"targetRefs,omitempty"`
	Spec       json.RawMessage `json:"spec"`
	Status     PolicyStatus    `json:"status"`
}

// PolicyStatus normalises the envoy-gateway extension's
// status.ancestors shape (one entry per resource the policy
// targets).
type PolicyStatus struct {
	Ancestors []PolicyAncestorStatus `json:"ancestors,omitempty"`
}

// PolicyAncestorStatus is one ancestor's reconciliation record.
type PolicyAncestorStatus struct {
	AncestorRef    json.RawMessage `json:"ancestorRef,omitempty"`
	ControllerName string          `json:"controllerName,omitempty"`
	Conditions     []Condition     `json:"conditions,omitempty"`
}

// Condition is the standard k8s condition shape. Subset of
// metav1.Condition that we actually need.
type Condition struct {
	Type    string `json:"type"`
	Status  string `json:"status"`
	Reason  string `json:"reason,omitempty"`
	Message string `json:"message,omitempty"`
}

// Fetch shells out to kubectl to read the cluster's reconciled
// gateway state and returns it as a populated *State. The
// returned object's JSON marshalling matches the schema in
// pkg/gateway/state.schema.json -- callers
// ship the result either to stdout (gateway state subcommand)
// or to <cacheDir>/<name>-gateway-state.json (prepare-export).
//
// One kubectl call per kind. Empty results (no Gateways at all,
// no HTTPRoutes, ...) are not errors -- the cluster might be
// pre-workload. The function returns slices that may be empty
// but never nil.
//
// kubectl context defaults to "local"; pass explicitly when
// snapshotting the appliance build cluster from a different
// shell.
func Fetch(ctx context.Context, kubectlContext string) (*State, error) {
	st := &State{
		Gateways:               []Gateway{},
		HTTPRoutes:             []HTTPRoute{},
		GRPCRoutes:             []GRPCRoute{},
		ClientTrafficPolicies:  []ClientTrafficPolicy{},
		BackendTrafficPolicies: []BackendTrafficPolicy{},
		FetchedAt:              time.Now().UTC().Format(time.RFC3339),
		SchemaID:               SchemaID,
		SchemaVersion:          SchemaVersion,
	}

	gc, err := fetchGatewayClass(ctx, kubectlContext)
	if err != nil {
		return nil, fmt.Errorf("fetch gatewayclass: %w", err)
	}
	st.GatewayClass = gc

	if err := fetchGateways(ctx, kubectlContext, st); err != nil {
		return nil, fmt.Errorf("fetch gateway: %w", err)
	}
	if err := fetchHTTPRoutes(ctx, kubectlContext, st); err != nil {
		return nil, fmt.Errorf("fetch httproute: %w", err)
	}
	if err := fetchGRPCRoutes(ctx, kubectlContext, st); err != nil {
		return nil, fmt.Errorf("fetch grpcroute: %w", err)
	}
	if err := fetchClientTrafficPolicies(ctx, kubectlContext, st); err != nil {
		return nil, fmt.Errorf("fetch clienttrafficpolicy: %w", err)
	}
	if err := fetchBackendTrafficPolicies(ctx, kubectlContext, st); err != nil {
		return nil, fmt.Errorf("fetch backendtrafficpolicy: %w", err)
	}

	// Summary is deterministic from the k8s-side slices we
	// just populated -- always built. Envoy is best-effort:
	// failing to reach a proxy pod doesn't fail the whole
	// snapshot (the user might be running this against a
	// pre-install cluster, or admin port-forward might be
	// blocked by a network policy). Surfacing FetchEnvoy's
	// error path to the caller would force them to special-
	// case "no proxy yet" everywhere; quietly skipping is
	// kinder. Real failures to investigate still print on
	// stderr from kubectl itself.
	st.Summary = BuildSummary(st)
	if env, err := FetchEnvoy(ctx, kubectlContext); err == nil {
		st.Envoy = env
	}
	return st, nil
}

// ClearDNSHintIPAnnotation removes the yolean.se/dns-hint-ip
// annotation from the y-cluster GatewayClass. Idempotent: if
// the annotation isn't there (or the GatewayClass doesn't
// exist), the function is a successful no-op.
//
// Used by prepare-export to strip the per-deploy IP from the
// appliance snapshot. Safe in that context because prepare-
// export is only invoked in the export flow, never against a
// cluster a developer is using interactively.
func ClearDNSHintIPAnnotation(ctx context.Context, kubectlContext, gatewayClassName string) error {
	if gatewayClassName == "" {
		gatewayClassName = "y-cluster"
	}
	// JSON-patch's remove op fails if the annotation isn't
	// present, so we do a describe-first to decide. The patch
	// path encodes "/" as ~1 (RFC 6901 JSON Pointer).
	annotation := envoygateway.DNSHintIPAnnotation
	jsonPath := strings.ReplaceAll(annotation, "/", "~1")
	out, err := runKubectl(ctx, kubectlContext,
		"get", "gatewayclass", gatewayClassName,
		"-o", "jsonpath={.metadata.annotations."+strings.ReplaceAll(annotation, ".", "\\.")+"}")
	if err != nil {
		return fmt.Errorf("describe gatewayclass: %w", err)
	}
	if len(bytes.TrimSpace(out)) == 0 {
		// Annotation absent (or GatewayClass missing -- both
		// fall through to the same no-op).
		return nil
	}
	patch := fmt.Sprintf(`[{"op":"remove","path":"/metadata/annotations/%s"}]`, jsonPath)
	if _, err := runKubectl(ctx, kubectlContext,
		"patch", "gatewayclass", gatewayClassName,
		"--type=json", "-p", patch); err != nil {
		return fmt.Errorf("patch gatewayclass: %w", err)
	}
	return nil
}

// runKubectl is the shared kubectl shellout helper. Stdout +
// stderr are combined; non-zero exit returns an error with the
// combined output for debugging.
func runKubectl(ctx context.Context, kubectlContext string, args ...string) ([]byte, error) {
	full := append([]string{"--context=" + kubectlContext}, args...)
	cmd := exec.CommandContext(ctx, "kubectl", full...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("kubectl %s: %s: %w", strings.Join(args, " "), out, err)
	}
	return out, nil
}

// kubectlGetJSON runs `kubectl get <kinds> -A -o json` and
// unmarshals into the supplied pointer (typically *itemList).
// Returns no error when the kind has zero items.
func kubectlGetJSON(ctx context.Context, kubectlContext, kindArg string, into any) error {
	out, err := runKubectl(ctx, kubectlContext, "get", kindArg, "-A", "-o", "json")
	if err != nil {
		return err
	}
	if err := json.Unmarshal(out, into); err != nil {
		return fmt.Errorf("unmarshal %s: %w", kindArg, err)
	}
	return nil
}
