#!/usr/bin/env bash
# Copy BuildKit's buildctl command (cmd/buildctl, package main) into
# pkg/buildctl, at the BuildKitVersion the dockerhost guest runs, and
# require the matching github.com/moby/buildkit module. Only buildctl's
# own source is copied; the rest of BuildKit stays a module dependency.
#
# Run after bumping BuildKitVersion in pkg/dockerhost/versions.go.
# --check exits non-zero when pkg/buildctl differs from what a refresh
# would write, without changing anything.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

check=false
[ "${1:-}" = "--check" ] && check=true

version=$(sed -n 's/^\tBuildKitVersion *= *"\(v[0-9.]*\)"$/\1/p' pkg/dockerhost/versions.go)
[ -n "$version" ] || { echo "no BuildKitVersion in pkg/dockerhost/versions.go" >&2; exit 1; }

src=$(go mod download -json "github.com/moby/buildkit@$version" | sed -n 's/^\t"Dir": "\(.*\)",$/\1/p')
[ -d "$src/cmd/buildctl" ] || { echo "no cmd/buildctl in github.com/moby/buildkit@$version" >&2; exit 1; }

out=$(mktemp -d)
trap 'rm -rf "$out"' EXIT

cp "$src/LICENSE" "$out/LICENSE"
for f in "$src"/cmd/buildctl/*.go; do
  case "$f" in *_test.go) continue ;; esac
  # Upstream's init functions set the process umask to 0 and global
  # state; compiled into y-cluster they would run for every subcommand,
  # so they become functions that Main calls.
  { echo "// Code generated by scripts/buildctl-refresh.sh from github.com/moby/buildkit@$version cmd/buildctl. DO NOT EDIT."
    echo
    sed -e 's/^package main$/package buildctl/' \
        -e 's/^func main() {$/func main(args []string) {/' \
        -e 's/app\.Run(context\.Background(), os\.Args)/app.Run(context.Background(), args)/' \
        -e "s/^func init() {\$/func init_$(basename "$f" .go)() {/" \
      "$f"
  } > "$out/$(basename "$f")"
done
grep -q 'app.Run(context.Background(), args)' "$out/main.go" \
  || { echo "cmd/buildctl/main.go no longer runs app.Run(context.Background(), os.Args): update this script" >&2; exit 1; }

inits=$(grep -ho '^func init_[a-z_]*()' "$out"/*.go | sed 's/^func //' | sort)
{
  echo "// Code generated by scripts/buildctl-refresh.sh from github.com/moby/buildkit@$version cmd/buildctl. DO NOT EDIT."
  echo
  echo "// Package buildctl is BuildKit's buildctl command, compiled into y-cluster."
  echo "// Licensed under the Apache License 2.0 (LICENSE in this directory)."
  echo "package buildctl"
  echo
  echo "import \"github.com/moby/buildkit/version\""
  echo
  echo "// Version is the BuildKit release this copy of buildctl comes from."
  echo "const Version = \"$version\""
  echo
  echo "// Main runs buildctl with args, args[0] being the program name, and"
  echo "// exits the process on error as buildctl does."
  echo "func Main(args []string) {"
  echo "	// set by BuildKit's release build, unset in a module dependency"
  echo "	version.Version = Version"
  for i in $inits; do echo "	$i"; done
  echo "	main(args)"
  echo "}"
} > "$out/zz_generated.go"
"$(go env GOROOT)/bin/gofmt" -w "$out"/*.go

if $check; then
  diff -r "$out" pkg/buildctl
  grep -q "github.com/moby/buildkit $version\$" go.mod \
    || { echo "go.mod does not require github.com/moby/buildkit $version" >&2; exit 1; }
  exit 0
fi

rm -rf pkg/buildctl
mkdir -p pkg/buildctl
cp "$out"/* pkg/buildctl/
go get "github.com/moby/buildkit@$version"
go mod tidy
