package hetzner

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"

	"go.uber.org/zap"

	"github.com/Yolean/y-cluster/pkg/sshexec"
)

// rejectUpstreamHostsToml is the per-registry containerd hosts.toml
// drop. Placed under
// /var/lib/rancher/k3s/agent/etc/containerd/certs.d/<registry>/
// for each major registry plus _default, this file makes containerd:
//
//  1. Treat the listed `server` as the original-registry fallback
//     (when a hosts.toml file is present in the registry's certs.d
//     directory, containerd does NOT fall back to the registry's
//     real hostname; it uses what's in the file). The `server` URL
//     resolves to RFC 6761's .invalid TLD, which never gets a DNS
//     answer.
//  2. List one host (the same dead URL) with pull/resolve
//     capabilities. When containerd tries the host, DNS fails;
//     because there's no other host AND no real-server fallback,
//     the pull errors out -- which is exactly what
//     imageCache.rejectUpstream is for.
//
// Why hosts.toml direct rather than k3s's registries.yaml
// translation: k3s converts `*: {endpoint: [...]}` into a
// _default/hosts.toml that DOES fall back to the original registry
// in practice (verified against k3s v1.35.4: a crictl pull for an
// uncached image succeeded despite the `*` mirror). hosts.toml
// direct is the documented containerd contract; we get
// deterministic behaviour regardless of k3s's translation logic.
//
// Trade: a `k3s server restart` regenerates certs.d from
// registries.yaml, which would re-apply the (less strict) wildcard
// translation. We drop both files (this hosts.toml AND
// registries.yaml) so post-restart behaviour stays correct, and
// the operator restart-loop ends up with the same lockdown.
const rejectUpstreamHostsToml = `# Generated by y-cluster (HetznerConfig.imageCache.rejectUpstream).
# All upstream pulls fail at DNS resolution. Pre-load the cache or
# use 'y-cluster images load' to bring images into containerd
# before Pod scheduling.
server = "http://reject-upstream-by-y-cluster.invalid:9999"

[host."http://reject-upstream-by-y-cluster.invalid:9999"]
  capabilities = ["pull", "resolve"]
`

// rejectUpstreamRegistriesYAML mirrors the same intent in k3s's
// registries.yaml format. Two reasons we ship both files:
//
//   - hosts.toml is what containerd consults at pull time and what
//     the e2e path validates (the file is the actual lockdown).
//   - registries.yaml is k3s's source-of-truth: a future `k3s
//     server restart` regenerates certs.d FROM this file, so if
//     we wrote only hosts.toml, post-restart behaviour drifts.
//     Keeping both in sync keeps the lockdown durable.
const rejectUpstreamRegistriesYAML = `# Generated by y-cluster (HetznerConfig.imageCache.rejectUpstream).
# Mirrored at /var/lib/rancher/k3s/agent/etc/containerd/certs.d/
# (per-registry hosts.toml drops); see HETZNER_PROVISIONER.md
# phase 6.d.
mirrors:
  "*":
    endpoint:
      - "http://reject-upstream-by-y-cluster.invalid:9999"
`

// rejectUpstreamRegistries is the explicit list of registries we
// drop a hosts.toml for. _default catches anything else; including
// the common ones explicitly is belt-and-braces against a k3s
// version where _default isn't honoured for a specific registry.
//
// Order is irrelevant for behaviour but kept stable for diff-
// readable script output.
var rejectUpstreamRegistries = []string{
	"_default",
	"docker.io",
	"registry.k8s.io",
	"quay.io",
	"ghcr.io",
	"gcr.io",
	"mcr.microsoft.com",
	"public.ecr.aws",
}

// rejectUpstreamScript renders the bash snippet the cluster node
// runs to apply the lockdown. Three steps:
//
//  1. Wait for the just-applied reaper Pod to reach Running -- if
//     the lockdown lands while kubelet is still pulling
//     hetznercloud/cli, the Pod ends up ImagePullBackOff and the
//     auto-teardown safety net is dead. The wait removes that
//     race.
//  2. Drop registries.yaml (k3s source-of-truth, durable across
//     k3s restarts).
//  3. Drop a per-registry hosts.toml -- the actual lockdown that
//     containerd consults per-pull, no k3s restart required.
//
// `set -euo pipefail` makes any failed sudo / write surface as a
// non-zero exit through SSH.
func rejectUpstreamScript() string {
	var b strings.Builder
	b.WriteString("set -euo pipefail\n")
	// (1) Wait for reaper. The Job is named "reaper" in
	// y-cluster-reaper namespace; its Pod gets the implicit
	// `job-name=reaper` label k8s adds. ~120s ceiling covers a
	// slow first-pull on a saturated link.
	b.WriteString("for i in $(seq 1 60); do\n")
	b.WriteString("  phase=$(sudo k3s kubectl -n y-cluster-reaper get pods -l job-name=reaper -o jsonpath='{.items[0].status.phase}' 2>/dev/null || true)\n")
	b.WriteString("  if [ \"$phase\" = \"Running\" ] || [ \"$phase\" = \"Succeeded\" ]; then break; fi\n")
	b.WriteString("  if [ \"$i\" = \"60\" ]; then echo \"reaper Pod did not reach Running within 120s; refusing to lock down upstream pulls\" >&2; exit 1; fi\n")
	b.WriteString("  sleep 2\n")
	b.WriteString("done\n")
	// (2) k3s registries.yaml.
	b.WriteString("sudo install -d -m 0755 /etc/rancher/k3s\n")
	b.WriteString("sudo tee /etc/rancher/k3s/registries.yaml >/dev/null <<'YCLUSTER_REGISTRIES_EOF'\n")
	b.WriteString(rejectUpstreamRegistriesYAML)
	b.WriteString("YCLUSTER_REGISTRIES_EOF\n")
	// (3) containerd hosts.toml drops -- the actual mechanism
	// that makes pulls fail.
	b.WriteString("sudo install -d -m 0755 /var/lib/rancher/k3s/agent/etc/containerd/certs.d\n")
	for _, reg := range rejectUpstreamRegistries {
		fmt.Fprintf(&b, "sudo install -d -m 0755 /var/lib/rancher/k3s/agent/etc/containerd/certs.d/%s\n", reg)
		fmt.Fprintf(&b, "sudo tee /var/lib/rancher/k3s/agent/etc/containerd/certs.d/%s/hosts.toml >/dev/null <<'YCLUSTER_HOSTS_EOF'\n", reg)
		b.WriteString(rejectUpstreamHostsToml)
		b.WriteString("YCLUSTER_HOSTS_EOF\n")
	}
	return b.String()
}

// applyRejectUpstream writes registries.yaml + per-registry
// hosts.toml on the node. No k3s restart required: containerd
// re-reads hosts.toml on each pull request, so the lockdown is
// effective immediately after the files land.
//
// Uses sshexec.Exec directly (not c.SSH) so the script body can
// be piped via stdin to `bash -s`, avoiding quoting hazards in
// the multi-line TOML payload.
func (c *Cluster) applyRejectUpstream(ctx context.Context) error {
	c.logger.Info("locking down upstream pulls (rejectUpstream)",
		zap.Strings("registries", rejectUpstreamRegistries))
	target := sshexec.Target{
		Host:    c.state.IPv4,
		Port:    "22",
		User:    c.cfg.SSHUser,
		KeyPath: filepath.Join(c.cacheDir, c.cfg.Context+"-ssh"),
	}
	out, err := sshexec.Exec(ctx, target, "bash -s", strings.NewReader(rejectUpstreamScript()))
	if err != nil {
		return fmt.Errorf("apply: %w; output=%s", err, string(out))
	}
	c.logger.Info("upstream pulls blocked; cache misses will now fail at containerd")
	return nil
}
